CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128) NOT NULL,
    password VARCHAR(512) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_username ON sys_user (username);

CREATE TABLE IF NOT EXISTS sys_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(128) NOT NULL,
    name VARCHAR(128) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_role_code ON sys_role (code);

CREATE TABLE IF NOT EXISTS sys_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(128) NOT NULL,
    name VARCHAR(128) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_permission_code ON sys_permission (code);

CREATE TABLE IF NOT EXISTS sys_user_role_ref (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_role_ref_user_role ON sys_user_role_ref (user_id, role_id);

CREATE TABLE IF NOT EXISTS sys_role_permission_ref (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_role_permission_ref_role_permission ON sys_role_permission_ref (role_id, permission_id);
